index/urls.py
from django.urls import include, path
from index import views

urlpatterns = [
    path('', views.index, name='index'),
    #path(r'^search/$', views.index, name='searcher')
]

parserdjango/urls.py
from django.contrib import admin
from django.urls import include, path
from index import views

urlpatterns = [
    path('', include('index.urls')),
    path('manipulation', include('log_files_manipulation.urls')),
    path('admin/', admin.site.urls),
]

index/forms.py
from django import forms

log_choice = [
    ('none', ' '),
    ('ip_addr', 'IP address'),
    ('status', 'Status'),
    ('size', 'Size')
    ]
class FilterForm(forms.Form):
    start_date = forms.DateField(label='')
    stop_date = forms.DateField(label='')
    search = forms.CharField(max_length=255)
    log_filter = forms.CharField(label = 'Filter', widget=forms.Select(choices=log_choice))

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <link rel="stylesheet"
            href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
            integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
            crossorigin="">
      <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
              integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
              crossorigin=""></script>

      <!-- Bootstrap CSS -->
      <link rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
            integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
            crossorigin="anonymous">

      <title>Parser log files</title>

      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
              integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
              crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
              integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
              crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
              integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
              crossorigin="anonymous"></script>

      <!-- Date picker -->
      <script src="https://unpkg.com/gijgo@1.9.11/js/gijgo.min.js"
              type="text/javascript"></script>
      <link href="https://unpkg.com/gijgo@1.9.11/css/gijgo.min.css"
            rel="stylesheet"
            type="text/css" />

      <link rel="stylesheet"
            href="{% static 'index/style.css' %}">


</head>

<body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand"
               href="#">Parser log files</a>
            <button class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse"
                 id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                              <a class="nav-link"
                                 href="{% url 'index' %}">Visualization <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                              <a class="nav-link"
                                 href="{% url 'manipulation' %}">Manipulation</a>
                        </li>
                        <li class="nav-item">
                              <a class="nav-link"
                                 href="{% url 'queryIp' %}">Find Ip</a>
                        </li>
                  </ul>
                  <!-- <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2"
                               type="search"
                               placeholder="Search"
                               aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0"
                                type="submit">Search</button> -->
                  </form>
            </div>
      </nav>
      <br>

      <!-- <div id="mapid"></div> -->
      {% block body_block %}
      {% endblock %}

      <!-- Optional JavaScript -->

      <script>
            $('#datepicker').datepicker();
            $('#id_start_date').datepicker();
            $('#id_stop_date').datepicker();
      </script>

      <!-- Map -->
      <script type="text/javascript"
              src="{% static 'index/index.js' %}">
            </script>

</body>

</html>